language: c
os: linux
dist: trusty
sudo: required
before_install:
- sudo .travis/register_apt_repositories.sh
- sudo apt-get install -y cross-mint-essential dos2unix lftp
- git --version
- make --version
- ld --version
- gcc --version
- m68k-atari-mint-ld --version
- m68k-atari-mint-gcc --version
- tar --version
- unix2dos --version
- lftp --version
script:
- make clean
- make all
- make release
before_deploy: 
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ${SECURE_KEY}
  file: libcmini*.tar.gz
  on:
    tags: true
    repo: mfro0/libcmini
